# Generated by Django 3.1 on 2020-08-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='humidity',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='update',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
